// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"plat_order/internal/dao/internal"
)

// internalNewUserDao is internal type for wrapping internal DAO implements.
type internalNewUserDao = *internal.NewUserDao

// newUserDao is the data access object for table new_user.
// You can define custom methods on it to extend its functionality as you wish.
type newUserDao struct {
	internalNewUserDao
}

var (
	// NewUser is globally public accessible object for table new_user operations.
	NewUser = newUserDao{
		internal.NewNewUserDao(),
	}
)

// Fill with you ideas below.
